-- Stage 3.12 — Warehouse staging contract

CREATE SCHEMA stg;

CREATE TABLE stg.silver_machine_telemetry (
    event_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    event_time DATETIME2(3) NOT NULL,
    ingestion_time DATETIME2(3) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    plant_id VARCHAR(20) NOT NULL,
    line_id VARCHAR(20) NOT NULL,
    machine_id VARCHAR(40) NOT NULL,
    machine_type VARCHAR(40) NULL,
    operating_state VARCHAR(30) NULL,
    correlation_id VARCHAR(200) NULL,
    causation_id VARCHAR(50) NULL,
    payload_sha256 VARCHAR(64) NOT NULL,
    simulator_run_id VARCHAR(40) NULL,
    scenario_id VARCHAR(60) NULL,
    scenario_instance_id VARCHAR(50) NULL,
    generation_sequence BIGINT NULL,
    ingestion_batch_id VARCHAR(68) NOT NULL,
    event_date DATE NOT NULL,
    processed_at_utc DATETIME2(3) NOT NULL,
    is_late_arrival BIT NOT NULL,
    event_payload_json VARCHAR(MAX) NOT NULL,
    temperature_c DECIMAL(18,6) NULL,
    vibration_mm_s DECIMAL(18,6) NULL,
    pressure_bar DECIMAL(18,6) NULL,
    spindle_rpm DECIMAL(18,6) NULL,
    power_kw DECIMAL(18,6) NULL,
    production_rate_unit_min DECIMAL(18,6) NULL,
    quality_score_pct DECIMAL(18,6) NULL,
    feed_rate_mm_min DECIMAL(18,6) NULL,
    hydraulic_pressure_bar DECIMAL(18,6) NULL,
    force_kn DECIMAL(18,6) NULL,
    cycle_time_s DECIMAL(18,6) NULL,
    motor_temperature_c DECIMAL(18,6) NULL,
    torque_nm DECIMAL(18,6) NULL,
    position_error_mm DECIMAL(18,6) NULL,
    motor_current_a DECIMAL(18,6) NULL,
    belt_speed_m_s DECIMAL(18,6) NULL,
    discharge_pressure_bar DECIMAL(18,6) NULL,
    rpm DECIMAL(18,6) NULL,
    chamber_temperature_c DECIMAL(18,6) NULL,
    fuel_flow_rate DECIMAL(18,6) NULL,
    pressure_mbar DECIMAL(18,6) NULL,
    inspection_cycle_time_s DECIMAL(18,6) NULL,
    measurement_deviation_mm DECIMAL(18,6) NULL,
    defect_probability_pct DECIMAL(18,6) NULL,
    equipment_temperature_c DECIMAL(18,6) NULL,
    throughput_unit_min DECIMAL(18,6) NULL
);

CREATE TABLE stg.silver_machine_operational_event (
    event_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    event_time DATETIME2(3) NOT NULL,
    ingestion_time DATETIME2(3) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    plant_id VARCHAR(20) NOT NULL,
    line_id VARCHAR(20) NOT NULL,
    machine_id VARCHAR(40) NOT NULL,
    machine_type VARCHAR(40) NULL,
    operating_state VARCHAR(30) NULL,
    previous_state VARCHAR(30) NULL,
    new_state VARCHAR(30) NULL,
    alarm_code VARCHAR(60) NULL,
    severity VARCHAR(30) NULL,
    fault_code VARCHAR(60) NULL,
    failure_mode_code VARCHAR(60) NULL,
    operator_id VARCHAR(40) NULL,
    work_order_id VARCHAR(60) NULL,
    correlation_id VARCHAR(200) NULL,
    causation_id VARCHAR(50) NULL,
    simulator_run_id VARCHAR(40) NULL,
    scenario_id VARCHAR(60) NULL,
    scenario_instance_id VARCHAR(50) NULL,
    generation_sequence BIGINT NULL,
    ingestion_batch_id VARCHAR(68) NOT NULL,
    event_date DATE NOT NULL,
    is_late_arrival BIT NOT NULL,
    is_planned BIT NULL,
    estimated_duration_seconds DECIMAL(18,3) NULL,
    communication_gap_seconds DECIMAL(18,3) NULL,
    event_payload_json VARCHAR(MAX) NOT NULL,
    payload_sha256 VARCHAR(64) NOT NULL,
    processed_at_utc DATETIME2(3) NOT NULL
);

CREATE TABLE stg.silver_production_event (
    event_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    event_time DATETIME2(3) NOT NULL,
    ingestion_time DATETIME2(3) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    plant_id VARCHAR(20) NOT NULL,
    line_id VARCHAR(20) NULL,
    machine_id VARCHAR(40) NULL,
    production_order_id VARCHAR(60) NOT NULL,
    batch_id VARCHAR(60) NULL,
    product_id VARCHAR(40) NULL,
    operation_id VARCHAR(60) NULL,
    production_sequence INT NULL,
    planned_quantity DECIMAL(18,4) NULL,
    actual_quantity DECIMAL(18,4) NULL,
    good_quantity DECIMAL(18,4) NULL,
    rejected_quantity DECIMAL(18,4) NULL,
    quantity_uom VARCHAR(20) NULL,
    planned_start_time DATETIME2(3) NULL,
    planned_end_time DATETIME2(3) NULL,
    actual_start_time DATETIME2(3) NULL,
    actual_end_time DATETIME2(3) NULL,
    pause_reason_code VARCHAR(60) NULL,
    loss_reason_code VARCHAR(60) NULL,
    loss_category VARCHAR(30) NULL,
    loss_quantity DECIMAL(18,4) NULL,
    loss_duration_seconds DECIMAL(18,3) NULL,
    downtime_event_id VARCHAR(50) NULL,
    machine_fault_event_id VARCHAR(50) NULL,
    correlation_id VARCHAR(200) NULL,
    causation_id VARCHAR(50) NULL,
    simulator_run_id VARCHAR(40) NULL,
    scenario_id VARCHAR(60) NULL,
    scenario_instance_id VARCHAR(50) NULL,
    generation_sequence BIGINT NULL,
    ingestion_batch_id VARCHAR(68) NOT NULL,
    event_date DATE NOT NULL,
    is_late_arrival BIT NOT NULL,
    event_payload_json VARCHAR(MAX) NOT NULL,
    payload_sha256 VARCHAR(64) NOT NULL,
    processed_at_utc DATETIME2(3) NOT NULL
);

CREATE TABLE stg.silver_maintenance_event (
    event_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    event_time DATETIME2(3) NOT NULL,
    ingestion_time DATETIME2(3) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    plant_id VARCHAR(20) NOT NULL,
    line_id VARCHAR(20) NULL,
    machine_id VARCHAR(40) NULL,
    work_order_id VARCHAR(60) NULL,
    technician_id VARCHAR(40) NULL,
    maintenance_type VARCHAR(30) NULL,
    failure_mode_code VARCHAR(60) NULL,
    spare_part_id VARCHAR(60) NULL,
    quantity_consumed DECIMAL(18,4) NULL,
    correlation_id VARCHAR(200) NULL,
    causation_id VARCHAR(50) NULL,
    simulator_run_id VARCHAR(40) NULL,
    scenario_id VARCHAR(60) NULL,
    scenario_instance_id VARCHAR(50) NULL,
    generation_sequence BIGINT NULL,
    ingestion_batch_id VARCHAR(68) NOT NULL,
    event_payload_json VARCHAR(MAX) NOT NULL,
    payload_sha256 VARCHAR(64) NOT NULL
);

CREATE TABLE stg.silver_quality_event (
    event_id VARCHAR(50) NOT NULL,
    event_type VARCHAR(100) NOT NULL,
    schema_version VARCHAR(20) NOT NULL,
    event_time DATETIME2(3) NOT NULL,
    ingestion_time DATETIME2(3) NOT NULL,
    source_system VARCHAR(100) NOT NULL,
    plant_id VARCHAR(20) NOT NULL,
    line_id VARCHAR(20) NULL,
    machine_id VARCHAR(40) NULL,
    production_order_id VARCHAR(60) NULL,
    batch_id VARCHAR(60) NULL,
    product_id VARCHAR(40) NULL,
    defect_code VARCHAR(60) NULL,
    severity VARCHAR(30) NULL,
    measurement_value DECIMAL(18,6) NULL,
    measurement_uom VARCHAR(30) NULL,
    disposition VARCHAR(30) NULL,
    correlation_id VARCHAR(200) NULL,
    causation_id VARCHAR(50) NULL,
    simulator_run_id VARCHAR(40) NULL,
    scenario_id VARCHAR(60) NULL,
    scenario_instance_id VARCHAR(50) NULL,
    generation_sequence BIGINT NULL,
    ingestion_batch_id VARCHAR(68) NOT NULL,
    event_payload_json VARCHAR(MAX) NOT NULL,
    payload_sha256 VARCHAR(64) NOT NULL
);
